SOHF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('charity/',include('charity.urls')),
    path('admin/', admin.site.urls),
    
] 

charity/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'sohf'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/',views.about, name='about' ),
    path('gallery/',views.gallery, name='gallery' ),
    path('projects/',views.projects, name='projects' ),
    path('contact/',views.contact, name='contact' ),
    path('<int:events_id>/', views.events, name='events'), 


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

charity/models.py
from django.db import models

# Create your models here.
class events(models.Model):
    event_name =  models.CharField(max_length=200) 
    event_date = models.DateTimeField('Event Date: ')
    
    def __str__(self):
        return self.event_name

charity/views.py
from django.shortcuts import render
import datetime
from .models import events

# Create your views here.
site = "SHEAVES OF HOPE FOUNDATION | "
def index(request):    
    page = "Home"
    return render(request,'index.html', {'page': page,'site':site})

def about(request):
    page = "About"
    date = datetime.date.today()
    return render(request,'about.html', {'page': page,'site':site, 'today':date,})

def gallery(request):
    page = "Gallery"
    return render(request,'gallery.html', {'page': page,'site':site})

def projects(request):
    page = "Projects"
    return render(request,'project.html', {'page': page,'site':site})

def contact(request):
    page = "Get in Touch"
    return render(request,'contact.html', {'page': page,'site':site})

def recents(request):
    recent_events_list = events.objects.order_by('event_date')[:5]
    context = {'recent_events_list': recent_events_list}
    return render(request, 'base.html', {'recent': context}) 

templates/about.html
{% extends 'base.html' %}
{% block title%} {{site}}{{page}} {% endblock %}
{% block content%} {{today}}{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {%endblock%}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
</head>
<body>
        <header>{%include 'header.html' %}</header>
        <main>
            <div class="content">
                {% block content %}{%endblock%}
            </div>
            <div class="sidebar">
                <div class="recent">
                    <h3>Recent Event</h3>
                    {% if recent_event_list %} 
                    <ul> 
                        {% for event in recent_event_list %} 
                        <li><a href="#">{{events.event_name}}</a></li>
                        {% endfor %} 
                    </ul> 
                    {% else %} <p>{{recent}}No recent events are available.</p> {% endif %}
                </div>
                <iframe src="https://twiter.com/sheaves_of_hope" frameborder="0">Twiter Feeds</iframe>
            </div>

        </main>
        <footer>{% include 'footer.html'%}</footer>
    
</body>
</html>

templates/footer.html
&copy;2019 SHEAVES OF HOPE FOUNDATION

templates/header.html
<div class="title">
        {% load static %}
    <span id="logo"><img src="{% static 'images/logo.png' %}" alt="sheave of hope logo"></span>
    <span id="pagetitle"><h2>{{site}}{{page}}</h2></span>
</div>
<nav>
    <ul>
        <li><a href="{% url 'sohf:index' %}">Home</a></li>
        <li><a href="{% url 'sohf:about' %}">About</a></li>
        <li><a href="#">Gallery</a></li>
        <li><a href="#">Projects</a></li>
        <li><a href="#">Get in Touch</a></li>
    </ul>
</nav>

templates/index.html
{% extends 'base.html' %}
{% block title%} {{site}}{{page}} {% endblock %}